### ISSUE TITLE
HOldings table too wide

### ISSUE THREAD

**Issue by FreeTrade** [HOdlcoin/HOdlcoin#21]
Causes horizontal scrollbar to appear on default width. Columns can be narrower to avoid this.

**Comment by Fuzzbawls** [comment]
what about making the default UI window width a bit wider?

**Comment by FreeTrade** [comment]
could do that too. although i assume the dimensions were chosen for some sensible reason. maybe not. I cut down the column width to 75, but some of the headers and getting cut off now.

**Comment by Fuzzbawls** [comment]
Basically resolved, but a more dynamic solution may be looked into for 1.0.1

**Comment by ghobson2013** [comment]
I looked at the code, I can set the column "resize mode" to "resizeToContents" which will basically match the column name length, and then the last column mode set to "Stretch" so that it fills the rest of the table width.
The advantage is that it will fix the current issue of truncated column names, the drawback is that the default table size will be the total length of all column names which is longer than the default wallet window size. Resizing will however stretch automatically out, and you can still manually resize the columns.   If you feel this is acceptable let me know , and i will make a pull request for it.

Note: we can also increase the default wallet window size, people dont have 800x600 screens anymore :)
