### ISSUE TITLE
Latest commit doesn't mine

### ISSUE THREAD

**Issue by michelem09** [HOdlcoin/HOdlcoin#73]
Hello,
after the include of the pallas fork changes `hodlcoind` doesn't start mine anymore. I saw this with the pallas fork too when I tried it few days ago.

This is my `hodlcoin.conf`:

```
rpcuser=rpc
rpcpassword=<pass>
server=1
port=1989
rpcport=11989
rpcallowip=127.0.0.1
daemon=1
gen=1
minermemory=4
genproclimit=8
miningaddress=<mywalletaddress>
```

I have built it with `--disable-wallet` don't know if this could be the problem, ~~but with the previous commit it worked fine~~ (it was a binary version the previous one I was using).
Feel free to ask more info.

**Comment by Fuzzbawls** [comment]
compiling with `--disable-wallet` bypasses the internal miner and the relevant rpc functions (among other things). This hasn't changed recently, and was a carryover behavior from the original forking from bitcoin.

Since HOdlcoin can mine to a non-associated address (ie, wallet functionality isn't technically a requirement), it could be feasible to allow the internal miner to be compiled in even if the wallet features are not. However, such changes would be a rather large undertaking.

It would be much quicker to compile the daemon with the wallet features enabled (requires Berkeley DB).

**Comment by michelem09** [comment]
I didn't know that. I'm trying to compile it with the wallet. Thanks.

**Comment by Fuzzbawls** [comment]
No problem and happy mining :)
